### ISSUE TITLE
No es compatible con PHP 8.2

### ISSUE THREAD

**Issue by Conrado2011** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#105]
Al culminar una compra te redirige al carrito vacío y en los logs aparece el siguiente error:

`"exception":"[object] (Exception(code: 0): Deprecated Functionality: Creation of dynamic property Transbank\\Webpay\\Observer\\EmailObserver::$_current_order is deprecated in /app/vxulksythc5nk_stg/vendor/transbank/webpay-magento2-rest/Observer/EmailObserver.php on line 16 at /app/vxulksythc5nk_stg/vendor/magento/framework/App/ErrorHandler.php:62)"} []`

**Comment by mastudillot** [comment]
Por ahora no es compatible con PHP sobre 8.x, debido a que el SDK todavía no tiene soporte, se esta haciendo la migración del SDK y luego se le dará a los plugins. Ya estamos trabajando en el soporte para el SDK.

**Comment by Conrado2011** [comment]
De acuerdo, aguardamos novedades, saludos!

**Comment by mastudillot** [comment]
Oficialmente, todavía no damos compatibilidad, pero se han eliminado todos los warnings que da con versiones de PHP 8.x en las últimas versiones.
