### ISSUE TITLE
Plugin magento presenta comportamiento no deseado en mails y retorno

### ISSUE THREAD

**Issue by jotalevi** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#12]
La instalación del plugin rest para magento ha presentado algunos comportamientos que no he podido resolver.

1- Mail de confirmación de compra se envía antes del pago, en el momento que el cliente le hace click al botón de ‘Pagar con Transbank’

2- Al finalizar el pago, transbank redirecciona al carrito de compras en ves de la pagina de suceso.

Para reproducir

1. Instalé el plugin en mi sitio y realice las configuraciones necesarias, seguido de algunos tweaks en las urls de inicio de transacción.
2. Desde ese entonces ambos bugs han sido constantes.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Latest
- Magento: 2.4ce
- PHP 7.4

**Comment by gdespirito** [comment]
Hola @taneto-OG . ¡Gracias por reportar!
Estaba revisando el código y no veo que se haga ningún envío, aunque puede que esté pasando algo por alto. 

¿Esto solo pasa si realizas estos "tweaks en la url de inicio de transacción"?

**Comment by erostalevi** [comment]
Si, con la versión original el modulo ni siquiera aparece en metodos de pago

**Comment by gdespirito** [comment]
Eso es raro, porque el módulo siempre lo probamos en una instalación nueva de magento y funciona sin problemas y aparece como medio de pago. Debe ser algo de tu instalación probablemente. 

Podríamos ayudarte de mejor forma son instrucciones claras para reproducir el bug :)

**Comment by gdespirito** [comment]
Ah, estás usando magento 2.4, ahora vi. No hemos probado en 2.4 ya que la última versión creo que se lanzó antes de que saliera Magento 2.4. Quizás el tema es poder agregar soporte a la 2.4.

**Comment by gdespirito** [comment]
Voy a probar en una instalación nueva de mangeto 2.4.

**Comment by ponda01** [comment]
Alguna Idea de como solucionar esto?

**Comment by cristianfrenkel** [comment]
Ya lo resolví... Lo parché directo en el vendor. Después veré si puedo aplicar una solución más elegante, pero básicamente esto es lo que hice:
/vendor/magento/module-sales/Model/Order/Email/Sender.php
Le agregué un if  antes del sender->send... Lo que hace que no me envíe el correo al crear el pedido:
        /** @var SenderBuilder $sender */
        $sender = $this->getSender();
        try {
            if($order->getStatus() == 'processing'){
            $sender->send();
            };
        }
Luego, en /vendor/transbank/webpay-magento2-rest/Controller/Transaction/CommitWebpayM22.php
Despues del $order->save(); de la línea 89 agregué:
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $objectManager->create('Magento\Sales\Model\OrderNotifier')->notify($order);

**Comment by cristianfrenkel** [comment]
¿No hay una solución oficial para esto? Traté de desarrollar un modulo que aplique el parche, pero se me complicó modificar el Sender y no me siento muy comodo teniendolo parchado en el vendor

**Comment by gdespirito** [comment]
Hola, 

Vamos a revisar porque se genera este comportamiento y que problema hay en al código del plugin que hace que pase esto. Si tienen más información, sería ideal.

**Comment by Markblu** [comment]
I have the same issue, 
installed version 1.1.2 on Magento 2.3.4, PHP 7.2.34.

The order confirmation email is send as soon as the customer clicks on webpay button.

**Comment by isabellaahc** [comment]
Hola a todos y muchas gracias por reportar.
Ya estamos revisando lo mencionado en este issue.
Esperamos tener noticias en breve.

**Comment by isabellaahc** [comment]
Estimados, revisamos este issue y el comportamiento de envío de correo no es generado por nuestro plugin sino que corresponde a una configuración de Magento aplicable en el menú Sales->Sales Emails. 
De todas formas, confirmamos que también existe una mejora que se puede aplicar al plugin para notificar el envío en caso de éxito en el pago de una orden.
Esta será incluida en una próxima versión del plugin.

**Comment by cristianfrenkel** [comment]
Hola @isabellaahc, ¿quoeres decir que en "Sales Emails" existe una configuración que permite que el correo de confirmación de compra salga con el pago exitoso y no antes de pagar?

Hasta donde yo pude investigar en el código, la opción que está en Sales Emails lo que dice es si enviar o no enviar el correo de confirmación, pero si se desactiva, no llega ni antes ni después del pago. Si se activa, llega antes del pago.

Entonces, mi solución ha sido bloquear por código el envío del correo de sistema, y agregarlo en forma manual luego de realizar el pago exitoso, pero esto debería hacerlo el módulo de transbank. Por ejemplo, el módulo de MercadoPago funciona en forma correcta en su notificación por correo.

**Comment by isabellaahc** [comment]
Exactamente, el correo con esa configuración no se envía ni antes ni después pero con esa configuración habilitada se envía siempre independiente de que el pago haya sido efectuado o no. 
Es una mejora que se debe agregar al plugin pero no se trata de un bug, la solución es como dices tu, habilitar en el plugin el envío de correo cuando el pago sea exitoso, sino se mal interpreta el correo.

**Comment by cristianfrenkel** [comment]
@isabellaahc entiendo que puede no ser considerado un bug propiamente tal, pero creo que es una función básica para el eCommerce de hoy que el correo se dispare con el pago confirmado y no antes. Ojalá lo puedan agregar. Son 2 líneas de código para disparar el correo, y el observer que modifique el comportamiento del Sender, que ese está un poco más complicado, pero otros ya lo han hecho con éxito. Saludos!

**Comment by isabellaahc** [comment]
Hola @cristianfrenkel, quizás me expresé mal. 
Si va a ser incluida como mejora en la próxima versión del plugin, además de la corrección de unos issues, solo fue cerrado como tal porque no aplica, ya estamos trabajando en mejorar este punto.
