### ISSUE TITLE
Desconfiguracion de panel de administracion en magento 2.3.6-p1

### ISSUE THREAD

**Issue by zapateroremendon** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#16]
**Describe el bug**
Al instalar el plugin de transbank se desajusta el estilo del panel de configuracion. El error se reproduce con instalacion limpia de magento 2.3.6-p1 y plantilla por defecto "Luma"

**Para reproducir**

1.- Al instalar el plugin mediante #composer require transbank/webpay-magento2-rest
2.- Ir al panel de administracion de magento
3.- Ir a por ejemplo store>configuration>general>general>

**Comportamiento observado**

![desalineacion](https://user-images.githubusercontent.com/37345629/113313493-ae082b80-92e1-11eb-92e4-0be10ca8406c.png)

**Comportamiento esperado**

![esperado](https://user-images.githubusercontent.com/37345629/113313517-b3fe0c80-92e1-11eb-8c92-329150667653.png)

Una explicación concisa y clara de qué es lo que esperas que ocurra.

**Versiones (por favor agrega aquí la siguiente información):**

- Plugin: 1.0.2
- Magento: 2.3.6-p1 luma theme
- PHP 7.3.27

**Comment by zapateroremendon** [comment]
Buenos dias,
¿Alguna novedad al respecto?

Muchas gracias !

**Comment by isabellaahc** [comment]
Hola @zapateroremendon estoy revisando el issue reportado y no veo que exista problemas con la versión del plugin actualmente disponible. No me queda claro la segunda imagen, ¿no estás pudiendo ver la información de configuración del plugin?
Agradeceré nos entregues más información para validar el error que reportas.

**Comment by Markblu** [comment]
hi @isabellaahc we have installed your module on Magento 2.3.4 and I can confirm that there are some css overwrite on Magento backend and this is some pages is quite problematic.

In attachment you can find an example, even if in this case the shadow is not a problematic bug, you can see that depends on bootstrap loaded by the Transbank plugin.

<img width="1679" alt="immagine" src="https://user-images.githubusercontent.com/8791143/125470715-4991a5ce-4b42-46ab-958f-9d2cfb824d8a.png">



Thanks a lot

**Comment by isabellaahc** [comment]
Gracias por reportar @zapateroremendon @Markblu 
Ya estamos trabajando para solucionar los issues reportados en esta versión del plugin. 
Les contaremos novedades en breve.

**Comment by JMLucas96** [comment]
Same issue as @Markblu here...
