### ISSUE TITLE
Error sesion administrador magento 2.3.6-p1

### ISSUE THREAD

**Issue by zapateroremendon** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#17]
Error se presenta el entrar al modulo en sesion de administrador store>configuration>sales>payment methods (aparece este error en pantalla) y clientes no pueden finalizar la compra.

Fatal error: Uncaught Error: Call to undefined method Transbank\Webpay\Options::defaultConfig() in /home/user/public_html/vendor/transbank/webpay-magento2-rest/Model/HealthCheck.php:21 Stack trace: #0 /home/user/public_html/vendor/transbank/webpay-magento2-rest/Block/System/Config/TbkButton.php(24): Transbank\Webpay\Model\HealthCheck->__construct(Array) #1 /home/user/public_html/generated/code/Transbank/Webpay/Block/System/Config/TbkButton/Interceptor.php(14): Transbank\Webpay\Block\System\Config\TbkButton->__construct(Object(Magento\Backend\Block\Template\Context), Object(Transbank\Webpay\Model\Config\ConfigProvider)) #2 /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Transbank\Webpay\Block\System\Config\TbkButton\Interceptor->__construct(Object(Magento\Backend\Block\Template\Context), Object(Transbank\Webpay\Model\Config\ConfigProvider)) #3 /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework in /home/user/public_html/vendor/transbank/webpay-magento2-rest/Model/HealthCheck.php on line 21

**Para reproducir**

1. Error se presenta despues de actualizar los modulos del plugin rest con "composer update"

- Plugin: [1.0.2]
- Magento: [2.3.6-p1]
- PHP [7.3.27]

**Contexto adicional**

logs de transbank :

2021-04-19T00:05:45+00:00 ERR (3): Error al crear transacción: Deprecated Functionality: Non-static method Transbank\Webpay\WebpayPlus\Transaction::create() should not be called statically in /home/user/public_html/vendor/transbank/webpay-magento2-rest/Model/TransbankSdkWebpayRest.php on line 60

**Comment by gdespirito** [comment]
Hola! Me parece que se instaló la versión 2.x del SDK, y este plugin requiere la 1.X. ¿Puedes forzar a que se use la versión 1.x? 
`composer require transbank/transbank-sdk:~1.10`

**Comment by zapateroremendon** [comment]
Gracias por sus comentarios @gonzunigad bajando la version se resuelve el problema.
