### ISSUE TITLE
Generar invoice al confirmar pago

### ISSUE THREAD

**Issue by iampolo87** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#24]
El modulo de magento 2 de wepay no genera invoices al completar los pagos, esto puede traer problemas. ¿Es adrede? 
Saludos

**Comment by gdespirito** [comment]
Hola. El plugin no hace nada relacionado a los invoice. Ni los hace ni los bloquea, en teoría.

**Comment by iampolo87** [comment]
> 
> 
> Hola. El plugin no hace nada relacionado a los invoice. Ni los hace ni los bloquea, en teoría.

Buenas! de hecho sí los bloquea, porque el pedido pasa a estado Completed, lo cual bloquea la generación de Invoice desde panel.
En mi caso, le agregue una generación de Invoice al controller antes de completar la orden, saludos.

**Comment by iampolo87** [comment]
Si pasa a completed sin generar un Invoice es un problema digamos, porque asi el pedido termina sin invoice. Quizas pasar a processing, o generar el invoice automáticamente.
Como dije, en mi caso le agregue la generación de Invoice con un preference.

**Comment by gdespirito** [comment]
Pero la duda es ¿porqué el medio de pago debería hacer eso? ¿Eso no es parte nativa del flujo de una orden en Magento?

**Comment by gdespirito** [comment]
¿Entonces en que estado deberían quedar para que se pueda generar manualmente?

**Comment by iampolo87** [comment]
Processing.

**Comment by gdespirito** [comment]
Pero revisando el plugin, eso es configurable.... 
Tu puedes configurar en que estado queda la orden luego de que se paga.

**Comment by iampolo87** [comment]
Ah si es verdad, es configurable.
La verdad es que me olvide totalmente, en mi caso particular el cliente queria que se complete la orden automáticamente, he ahi el problema.
Gracias!

**Comment by gdespirito** [comment]
No hay problema!
