### ISSUE TITLE
Module force checkout layout to a non standard "1column"

### ISSUE THREAD

**Issue by Markblu** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#27]
The plugin change the standard layout of checkout to "1column" layout, as results in checkout is added "header-wrapper" and "footer-container". 

**Para reproducir**

1. Get a fresh Magento installation
2. Use standard Luma o Blank theme
3. Install the transbank plugin
4. add a product to cart and go to checkout

**Comportamiento observado**

The layout of checkout page is changed, header and footer appears. 

**Comportamiento esperado**

The layout of checkout page should not change. 

**Capturas de pantalla**

![immagine](https://user-images.githubusercontent.com/8791143/126649391-e49cf43f-cc7d-490d-88fc-ac22ee46e0f3.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.1.2
- Magento: 2.3.4
- PHP 7.2.34

**Contexto adicional**

Please check view/adminhtml/layout/adminhtml_system_config_edit.xml in line 2:
1. there in an error in xml tag is written "pagepage" instead of "page"
2. layout is forced to "1column"

Thanks a lot

**Comment by HeikelV** [comment]
In this case, what would be the appropriate behavior? Show or not show the header and footer? like this picture??

![2021-08-03_02-23](https://user-images.githubusercontent.com/8449422/127967887-49a28920-6f12-42e4-acfc-9f1415731cad.png)

**Comment by isabellaahc** [comment]
Hola a todos! Este issue fue solucionado en la versión 1.1.4 del plugin.
Muchas gracias por reportar 🎉
