### ISSUE TITLE
Wont show on Admin or throw exception

### ISSUE THREAD

**Issue by Francisco-Huerta** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#32]
The plugin will show exception after clean install
The plugin wont show after clean install and `composer update` command

PHP 7.4.26
Magento 2.4.3-p1
Zend Engine v3.4.0

Para reproducir

    Get a fresh Magento installation
    Use standard Luma or Blank theme
    Install the transbank plugin

Comportamiento observado

The plugin will output exception or wont show after entering Stores/Configuration/Sales/Payment Methods

Comportamiento esperado

The plugin should show

Solution / work around

Installing another extension will make the plugin to show

**Comment by ludcl** [comment]
Same issue here. It's not being shown even after installing another extension. The workaround didn't worked for me.
--
Me pasó lo mismo. El módulo no se muestra incluso después de instalar un módulo diferente. El workaround no me funcionó.

**Comment by isabellaahc** [comment]
Hi @Francisco-Huerta, the error could not be replicated, are you still having the same problem?
