### ISSUE TITLE
api not work rset inmagento 2

### ISSUE THREAD

**Issue by sagar364490** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#40]
**Describe el bug**

Una descripción concisa sobre el bug.

**Para reproducir**

1. Configura '...'
2. Haz click en '...'
3. Baja hasta '...'
4. Se ve el error en '...'

**Comportamiento observado**

Describe de forma concisa lo que observaste siguiendo los pasos para reproducir el error.

**Comportamiento esperado**

Una explicación concisa y clara de qué es lo que esperas que ocurra.

**Capturas de pantalla**

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: [ej. 3.1.12]
- Magento: [ej. 2.0]
- PHP [ej. 7.1]

**Contexto adicional**

Agrega cualquier otro información sobre el problema aquí.

**Comment by sagar364490** [comment]
i have install webpay rest api but not work

**Comment by isabellaahc** [comment]
@sagar364490, we need more information to validate. Please send us:

    Plugin: [ej. 3.1.12]
    Magento: [ej. 2.0]
    PHP [ej. 7.1]
