### ISSUE TITLE
Problema de instalación en Magento 2.4.4

### ISSUE THREAD

**Issue by mauricechile** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#42]
**Describe el bug**

Cuando lnstalo el Plugin con el composer para Magento 2.4.4 arroja el siguiente error:

![image](https://user-images.githubusercontent.com/80056767/171296174-562b2499-74e9-46fe-b458-04491a0831ac.png)

magento/product-community-edition is locked to version 2.4.4 and an update                          of this package was not requested.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.2.4 
- Magento: 2.4.4
- PHP 8.1

**Contexto adicional**

Por favor me pueden comentar cual sería el problema principal o si lo pueden probar con Magento 2.4.4 (Versión Luma)

Muchas gracias

**Comment by isabellaahc** [comment]
Hola @mauricechile, primero te pido disculpas por la demora en la respuesta. 
El plugin no ha sido probado con versiones superiores a php 8, vamos a hacer las pruebas para descartar problemas de compatibilidad con la información que nos comentas. La duda que me queda es que no encuentro la versión que nos comentas del plugin en el listado de releases, ¿podrías confirmarnos ese dato?

**Comment by mauricechile** [comment]
Hola @isabellaahc  por fin alguien me responde! (fueron casi 2 meses) gracias!!!!

Si quieres prueba la versión: 1.1.4 released this 26 Jan 2022  (https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/releases/tag/1.1.4)

Lo hice por "archivo" ya que por composer es imposible instalar esta extensión en esta versión de Magento 2.4.4 (no lo permite, por varias razones)

1) Descomprí la carpeta de archivos para que quedará en: app/code/Transbank/WebpayRes
2) Luego en edite el archivo app/etc/config.php y agrega Transbank_Webpay_Rest => 1 a la lista de módulos.

Luego en consola hice lo siguiente:
3) bin/magento setup:upgrade   
2) bin/magento cache:flush                      
3) php bin/magento indexer:reindex

Importante es Magento: 2.4.4 y PHP 8.1

Ahora te explico, adjunto la primera imagen ya que instalé en menos de 10 minutos sin problema el método de Pago Checkout de Verifone para Magento2 y en la segunda imagen luego de instalar Webpay Rest plugin para Magento2 se queda esa sección en blanco. Claramente hay un error.
![1 instale checkout](https://user-images.githubusercontent.com/80056767/184042371-60cd4271-2366-4162-848b-c218ac59d460.png)
![2Magento-con-transbank-error](https://user-images.githubusercontent.com/80056767/184042398-a5370cfa-31ca-41be-bb42-c37f6f66f687.png)

Quedo atento. Gracias

**Comment by mauricechile** [comment]
@isabellaahc are you there?
