### ISSUE TITLE
Solicitud para habilitar checkout con moneda según configuracion de vista de tienda

### ISSUE THREAD

**Issue by Richardmaximun** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#46]
El modulo actualmente toma la moneda base de la plataforma e ignora la moneda del store_view (logicamente siempre hablando del peso chileno)

Caso:

Plataforma con moneda base dolar
Monedas permitidas: Dolar americano y Peso chileno
Website 1 ->Store_View->Global: con moneda base dolar y moneda permitida dolar americano (Paypal)
Website 2 ->Store_View->Chile: con moneda base peso chileno y moneda permitida peso chileno (WebPay)

Tiendas:
![158863424-c26482bf-371a-481d-a620-50d146d33bfd](https://user-images.githubusercontent.com/5508014/181392106-55c957f2-1ed8-458b-adf2-20326f64c954.png)

Configuracion predeterminada:
![158863822-43fc0034-36de-434c-9208-1727e89e4122](https://user-images.githubusercontent.com/5508014/181392158-8eef9481-2968-4d52-b900-93e2a7975285.png)

Configuracion del Website->Store_view->Chile:
![158864318-094a8e68-ac16-49bb-bb97-95a0e3c1b947](https://user-images.githubusercontent.com/5508014/181392210-86b90a9b-f758-4581-81b1-ff381a75b2c8.png)

Escenario:

- A pesar de estar el Website->Store_view->Chile configurado con moneda peso chileno, el modulo no lo toma en cuenta como elegible para pago con WebPay porque está basado en la moneda base de plataforma

Solicitud:

- Habilitar la posibilidad de que WebPay, para el chekcout, pueda tomar la moneda del Website o Store_View que generó la Orden (siempre y cuando sea pesos chileno y esté habilitado en la configuracion para dicho Website/Store)

**Comment by isabellaahc** [comment]
Hola @Richardmaximun, gracias por proponer esta mejora para el módulo webpay. En este momento nos encontramos trabajando en una nueva funcionalidad para el plugin de Magento, por lo que agregaremos al backlog esta propuesta para agregarla en un futuro release.

**Comment by mvarlic** [comment]
Hola! encontré un link que te puede ayudar: https://bsscommerce.com/blog/base-currency-and-display-currency-in-magento-2/

Adicionalmente:



[multiple_moneda_magento.pdf](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/files/12860877/multiple_moneda_magento.pdf)
