### ISSUE TITLE
Al cancelar la orden en un Observer, el proceso de pago continúa de todas formas

### ISSUE THREAD

**Issue by fdo36** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#6]
**Describe el bug**

Tengo registrado un Observer que "escucha" al evento "sales_order_place_before". El Observer envía un request a otro endpoint y si la response tiene algún error, cancelo la orden y redirecciono al carrito de compras mostrando el mensaje de error.

Esto funcionaba bien hasta que instalé el plugin de transbank. No se ejecuta el redireccionamiento y continúa con el proceso de pago de transbank

**Para reproducir**

1. Registra un observer con el evento "sales_order_place_before"
2. En el código del Observer, redirecciona al carrito de compras luego de cancelar la orden
```
public function execute (Observer $observer) 
{
    $observer->getEvent()->getOrder()->cancel();
    $redirectionUrl = $this->url->getUrl('/checkout/cart/index');
    $this->responseFactory->create()->setRedirect($redirectionUrl)->sendResponse();
    exit;
}
```
3. Procede a efectuar una compra de prueba y selecciona transbank como método de pago
4. Luego del "place order" no redirecciona al carrito de compras (como si lo hace al seleccionar otro método de pago incluído en Magento)

**Comportamiento observado**

Luego del "place order" no redirecciona al carrito de compras (como si lo hace al seleccionar otro método de pago incluído en Magento)

**Comportamiento esperado**

Luego del "place order" debería redireccionar al carrito de compras (como si lo hace al seleccionar otro método de pago incluído en Magento)

**Versiones:**
- Plugin: 3.3.0
- Magento: 2.4.0
- PHP: 7.3.17

**Comment by fdo36** [comment]
tuve que dejar de lado la idea de redirigir al carrito de compras y solamente detengo la ejecución con 

`throw new StateException(__('Mensaje de Error'));`

Y se muestra el error en la misma página del checkout.

No se si esto sea para cerrar el issue?.

Saludos

**Comment by gdespirito** [comment]
Hola @fdo36. Gracias por reportar. 
Realmente no se si considerar esto un bug. Que bueno que al menos con el exception pudiste resolverlo. 
¿En otros medios de pago te funciona la redirección al carro?

**Comment by fdo36** [comment]
he probado con el medio de pago habilitado por defecto en Magento 2.4 y claro, funciona como es esperado.

de todas formas, no se si poner el exception sea lo más limpio para abordar el tema, pero de que funciona, funciona.

**Comment by gdespirito** [comment]
¿Que podríamos hacerle al plugin para que te permita hacer la redirección y detener la venta? 
Quizás podrías mandar un Pull Request con el cambio para que lo podamos revisar, aprobar y  quedes como contribuidor si es algo que le sirve a todos eventualmente.

**Comment by fdo36** [comment]
Vale perfecto, es algo que tengo en mente apenas tenga tiempo de revisarlo bien. Por mientras el approach que hice fue usando un plugin (interceptor) en vez de un simple observer. Detengo toda la ejecución con el exception y no se invoca a transbank cuando detengo todo. 

Apenas refactorice y vea como evitar usar el exception y si tengo que modificar algo en el modulo mismo, les envío el PR
