### ISSUE TITLE
No aparece la configuración en Magento 2.4.3 multiwebsite

### ISSUE THREAD

**Issue by SoyLinux** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#64]
Luego de varios problemas  para instalar el módulo (no creaba las tablas en la base de datos), logré instalarlo, pero no veo opciones en el panel de administración en "Payment Methods" Aparecen los nativos de Magento y alguno adicional, pero no Transbank.
La moneda del website es CLP, y no tengo ningún error en los logs.
Las instrucciones que seguí son las que figuran en:

https://www.transbankdevelopers.cl/plugin/magento/#

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Transbank_Webpay 2.1.1
- Magento: 2.4.3 CE
- PHP 7.4
-

Multiwebsite (distintos países en cada website.), la moneda del website es CLP.
Saludos

**Comment by jcasalins** [comment]
El problama esta en estos dos archivos
Transbank\Webpay\Model\Config\ConfigProvider.php
Transbank\Webpay\Observer\SaveConfigObserver.php

la raiz de problema es que el scopeConfig lo dejaron con el valor de default (0), por eso nunca va a tomar los cambio de las multisite

Saludos.

**Comment by mastudillot** [comment]
Por ahora no hay planes de dar compatibilidad con multitienda :(
